package mom.entities;

// Generated 16 May, 2016 12:35:57 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CommonMasterId generated by hbm2java
 */
@Embeddable
public class CommonMasterId implements java.io.Serializable {

	private int commonId;
	private int commonSubId;
	private String description;
	private Date updDate;
	private Integer version;

	public CommonMasterId() {
	}

	public CommonMasterId(int commonId, int commonSubId, String description,
			Date updDate) {
		this.commonId = commonId;
		this.commonSubId = commonSubId;
		this.description = description;
		this.updDate = updDate;
	}

	public CommonMasterId(int commonId, int commonSubId, String description,
			Date updDate, Integer version) {
		this.commonId = commonId;
		this.commonSubId = commonSubId;
		this.description = description;
		this.updDate = updDate;
		this.version = version;
	}

	@Column(name = "common_id", nullable = false)
	public int getCommonId() {
		return this.commonId;
	}

	public void setCommonId(int commonId) {
		this.commonId = commonId;
	}

	@Column(name = "common_sub_id", nullable = false)
	public int getCommonSubId() {
		return this.commonSubId;
	}

	public void setCommonSubId(int commonSubId) {
		this.commonSubId = commonSubId;
	}

	@Column(name = "description", nullable = false, length = 40)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "upd_date", nullable = false, length = 19)
	public Date getUpdDate() {
		return this.updDate;
	}

	public void setUpdDate(Date updDate) {
		this.updDate = updDate;
	}

	@Column(name = "version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CommonMasterId))
			return false;
		CommonMasterId castOther = (CommonMasterId) other;

		return (this.getCommonId() == castOther.getCommonId())
				&& (this.getCommonSubId() == castOther.getCommonSubId())
				&& ((this.getDescription() == castOther.getDescription()) || (this
						.getDescription() != null
						&& castOther.getDescription() != null && this
						.getDescription().equals(castOther.getDescription())))
				&& ((this.getUpdDate() == castOther.getUpdDate()) || (this
						.getUpdDate() != null && castOther.getUpdDate() != null && this
						.getUpdDate().equals(castOther.getUpdDate())))
				&& ((this.getVersion() == castOther.getVersion()) || (this
						.getVersion() != null && castOther.getVersion() != null && this
						.getVersion().equals(castOther.getVersion())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCommonId();
		result = 37 * result + this.getCommonSubId();
		result = 37
				* result
				+ (getDescription() == null ? 0 : this.getDescription()
						.hashCode());
		result = 37 * result
				+ (getUpdDate() == null ? 0 : this.getUpdDate().hashCode());
		result = 37 * result
				+ (getVersion() == null ? 0 : this.getVersion().hashCode());
		return result;
	}

}
