package mom.entities;

// Generated 16 May, 2016 12:35:57 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * MeetingRooms generated by hbm2java
 */
@Entity
@Table(name = "meeting_rooms", catalog = "mom")
public class MeetingRooms implements java.io.Serializable {

	private Integer roomId;
	private Integer version;
	private String roomName;
	private Date updDate;
	private Set<Mom> moms = new HashSet<Mom>(0);

	public MeetingRooms() {
	}

	public MeetingRooms(String roomName, Date updDate) {
		this.roomName = roomName;
		this.updDate = updDate;
	}

	public MeetingRooms(String roomName, Date updDate, Set moms) {
		this.roomName = roomName;
		this.updDate = updDate;
		this.moms = moms;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "room_id", unique = true, nullable = false)
	public Integer getRoomId() {
		return this.roomId;
	}

	public void setRoomId(Integer roomId) {
		this.roomId = roomId;
	}

	@Version
	@Column(name = "version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@Column(name = "room_name", nullable = false, length = 40)
	public String getRoomName() {
		return this.roomName;
	}

	public void setRoomName(String roomName) {
		this.roomName = roomName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "upd_date", nullable = false, length = 19)
	public Date getUpdDate() {
		return this.updDate;
	}

	public void setUpdDate(Date updDate) {
		this.updDate = updDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "meetingRooms")
	public Set<Mom> getMoms() {
		return this.moms;
	}

	public void setMoms(Set<Mom> moms) {
		this.moms = moms;
	}

}
