package mom.entities;

// Generated 16 May, 2016 12:35:57 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MomActionOwnerId generated by hbm2java
 */
@Embeddable
public class MomActionOwnerId implements java.io.Serializable {

	private long momId;
	private int actionId;
	private String userId;

	public MomActionOwnerId() {
	}

	public MomActionOwnerId(long momId, int actionId, String userId) {
		this.momId = momId;
		this.actionId = actionId;
		this.userId = userId;
	}

	@Column(name = "mom_id", nullable = false)
	public long getMomId() {
		return this.momId;
	}

	public void setMomId(long momId) {
		this.momId = momId;
	}

	@Column(name = "action_id", nullable = false)
	public int getActionId() {
		return this.actionId;
	}

	public void setActionId(int actionId) {
		this.actionId = actionId;
	}

	@Column(name = "user_id", nullable = false, length = 40)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MomActionOwnerId))
			return false;
		MomActionOwnerId castOther = (MomActionOwnerId) other;

		return (this.getMomId() == castOther.getMomId())
				&& (this.getActionId() == castOther.getActionId())
				&& ((this.getUserId() == castOther.getUserId()) || (this
						.getUserId() != null && castOther.getUserId() != null && this
						.getUserId().equals(castOther.getUserId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getMomId();
		result = 37 * result + this.getActionId();
		result = 37 * result
				+ (getUserId() == null ? 0 : this.getUserId().hashCode());
		return result;
	}

}
