package mom.entities;

// Generated 16 May, 2016 12:35:57 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MomActionsId generated by hbm2java
 */
@Embeddable
public class MomActionsId implements java.io.Serializable {

	private long momId;
	private int actionId;

	public MomActionsId() {
	}

	public MomActionsId(long momId, int actionId) {
		this.momId = momId;
		this.actionId = actionId;
	}

	@Column(name = "mom_id", nullable = false)
	public long getMomId() {
		return this.momId;
	}

	public void setMomId(long momId) {
		this.momId = momId;
	}

	@Column(name = "action_id", nullable = false)
	public int getActionId() {
		return this.actionId;
	}

	public void setActionId(int actionId) {
		this.actionId = actionId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MomActionsId))
			return false;
		MomActionsId castOther = (MomActionsId) other;

		return (this.getMomId() == castOther.getMomId())
				&& (this.getActionId() == castOther.getActionId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getMomId();
		result = 37 * result + this.getActionId();
		return result;
	}

}
