package mom.entities;

// Generated 16 May, 2016 12:35:57 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * MomDiscussions generated by hbm2java
 */
@Entity
@Table(name = "mom_discussions", catalog = "mom")
public class MomDiscussions implements java.io.Serializable {

	private MomDiscussionsId id;
	private Integer version;
	private Mom mom;
	private String discussion;
	private Date updDate;
	private String description;

	public MomDiscussions() {
	}

	public MomDiscussions(MomDiscussionsId id, Mom mom, String discussion,
			Date updDate, String description) {
		this.id = id;
		this.mom = mom;
		this.discussion = discussion;
		this.updDate = updDate;
		this.description = description;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "momId", column = @Column(name = "mom_id", nullable = false)),
			@AttributeOverride(name = "discussionId", column = @Column(name = "discussion_id", nullable = false)) })
	public MomDiscussionsId getId() {
		return this.id;
	}

	public void setId(MomDiscussionsId id) {
		this.id = id;
	}

	@Version
	@Column(name = "version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "mom_id", nullable = false, insertable = false, updatable = false)
	public Mom getMom() {
		return this.mom;
	}

	public void setMom(Mom mom) {
		this.mom = mom;
	}

	@Column(name = "discussion", nullable = false, length = 1)
	public String getDiscussion() {
		return this.discussion;
	}

	public void setDiscussion(String discussion) {
		this.discussion = discussion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "upd_date", nullable = false, length = 19)
	public Date getUpdDate() {
		return this.updDate;
	}

	public void setUpdDate(Date updDate) {
		this.updDate = updDate;
	}

	@Column(name = "description", nullable = false, length = 256)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
