package mom.entities;

// Generated 16 May, 2016 12:35:57 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MomRecipientsId generated by hbm2java
 */
@Embeddable
public class MomRecipientsId implements java.io.Serializable {

	private long momId;
	private String userId;

	public MomRecipientsId() {
	}

	public MomRecipientsId(long momId, String userId) {
		this.momId = momId;
		this.userId = userId;
	}

	@Column(name = "mom_id", nullable = false)
	public long getMomId() {
		return this.momId;
	}

	public void setMomId(long momId) {
		this.momId = momId;
	}

	@Column(name = "user_id", nullable = false, length = 40)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MomRecipientsId))
			return false;
		MomRecipientsId castOther = (MomRecipientsId) other;

		return (this.getMomId() == castOther.getMomId())
				&& ((this.getUserId() == castOther.getUserId()) || (this
						.getUserId() != null && castOther.getUserId() != null && this
						.getUserId().equals(castOther.getUserId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getMomId();
		result = 37 * result
				+ (getUserId() == null ? 0 : this.getUserId().hashCode());
		return result;
	}

}
